# Generated by Django 5.2.1 on 2025-06-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Detail', '0002_alter_background_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Background',
            new_name='Detail_Background_Img',
        ),
    ]
