# Generated by Django 5.1.7 on 2025-06-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Detail', '0003_rename_background_detail_background_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail_Background_Img',
        ),
    ]
