# Generated by Django 5.1.7 on 2025-06-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Detail', '0004_delete_detail_background_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='BG_Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Image', models.ImageField(upload_to='photo/')),
            ],
        ),
    ]
