# Generated by Django 5.1.6 on 2025-03-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Second_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Second_img', models.CharField(max_length=20)),
                ('Second_picture', models.ImageField(upload_to='photo/')),
            ],
        ),
    ]
