# Generated by Django 5.1.7 on 2025-03-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_second_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bible_random',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bible_name', models.CharField(max_length=30)),
                ('Main_verse', models.TextField()),
            ],
        ),
    ]
