# Generated by Django 5.1.7 on 2025-03-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_bible_random'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bible_random',
            new_name='Bible_quote',
        ),
        migrations.RenameField(
            model_name='bible_quote',
            old_name='Bible_name',
            new_name='BibleName',
        ),
        migrations.RenameField(
            model_name='bible_quote',
            old_name='Main_verse',
            new_name='MainVerse',
        ),
    ]
