# Generated by Django 5.1.7 on 2025-03-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_rename_bible_random_bible_quote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Image_main', models.ImageField(upload_to='photo/')),
            ],
        ),
    ]
