# Generated by Django 5.1.7 on 2025-03-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_background_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background_upload',
            name='Image_main',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
