# Generated by Django 5.1.7 on 2025-03-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_alter_background_upload_image_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='bible_quote',
            name='create',
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
