# Generated by Django 5.1.7 on 2025-03-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_bible_quote_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Picture', models.ImageField(upload_to='photo/Service')),
            ],
        ),
    ]
