# Generated by Django 5.1.7 on 2025-03-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Picture', models.ImageField(blank=True, null=True, upload_to='photo/')),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
