# Generated by Django 5.1.7 on 2025-04-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0009_service_data_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
