# Generated by Django 5.1.7 on 2025-04-04 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0010_news_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('title', models.CharField(max_length=30)),
                ('Post_items', models.FileField(upload_to='DailyPost/')),
                ('Descrtion', models.TextField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Website.news_catagory')),
            ],
        ),
    ]
