# Generated by Django 5.1.7 on 2025-04-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0011_news_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news_post',
            old_name='Descrtion',
            new_name='Descrption',
        ),
    ]
