# Generated by Django 5.1.7 on 2025-04-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0012_rename_descrtion_news_post_descrption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='Post_items',
            field=models.FileField(blank=True, null=True, upload_to='File/'),
        ),
    ]
