# Generated by Django 5.1.7 on 2025-04-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0013_alter_news_post_post_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_post',
            name='Post_img',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/'),
        ),
    ]
