# Generated by Django 5.1.7 on 2025-04-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0014_news_post_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_post',
            name='Post_items',
        ),
    ]
