# Generated by Django 5.1.7 on 2025-04-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0015_remove_news_post_post_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='Post_img',
            field=models.ImageField(upload_to='Photo/'),
        ),
    ]
