# Generated by Django 5.1.7 on 2025-04-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0016_alter_news_post_post_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('Img', models.ImageField(upload_to='footer_img/')),
            ],
        ),
    ]
