# Generated by Django 5.1.7 on 2025-06-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0017_footer_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
    ]
