# Generated by Django 5.1.7 on 2025-06-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0018_news_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News_category',
            new_name='Service_category',
        ),
    ]
