# Generated by Django 5.1.7 on 2025-06-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0019_rename_news_category_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Event_Img', models.ImageField(upload_to='Event/')),
            ],
        ),
    ]
