# Generated by Django 5.1.7 on 2025-06-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0020_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Event_Img',
            new_name='Event_pic',
        ),
    ]
