# Generated by Django 5.1.7 on 2025-06-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0021_rename_event_img_event_event_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
