# Generated by Django 5.1.7 on 2025-06-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0022_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regular_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_field', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('Day_Name', models.CharField(max_length=15)),
                ('Discription', models.TextField()),
                ('Regular_Img', models.ImageField(upload_to='Regular/')),
            ],
        ),
    ]
