# Generated by Django 5.1.7 on 2025-06-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0023_regular_program'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regular_program',
            new_name='Regular_program_Container',
        ),
    ]
