# Generated by Django 5.1.7 on 2025-06-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0024_rename_regular_program_regular_program_container'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regular_program_Container',
        ),
    ]
